//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasualConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasualConsole.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asd,24,&quot;hel,lo&quot;,bla bla bla,&quot;yet another example where he said &quot;&quot;hi!&quot;&quot;, can you believe it?&quot;,24.5.
        /// </summary>
        public static string CsvText {
            get {
                return ResourceManager.GetString("CsvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;item&gt;
        ///			&lt;title&gt;YGOTAS Episode 75 - Valley of the Duels&lt;/title&gt;
        ///			&lt;link&gt;https://www.youtube.com/watch?v=YSAiv93D7jg&lt;/link&gt;
        ///			&lt;description&gt;It&apos;s a good thing I played all that YouTubers Life. Special thanks to Krosecz for editing this episode! Check out Krosecz&apos;s channel at ...&lt;/description&gt;
        ///			&lt;pubDate&gt;Tue, 20 Jun 2017 15:55:19 GMT&lt;/pubDate&gt;
        ///		&lt;/item&gt;
        ///		&lt;item&gt;
        ///			&lt;title&gt;Episode 74 - Right In The Feels&lt;/title&gt;
        ///			&lt;link&gt;https://www.yout [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ErrorContainingXml {
            get {
                return ResourceManager.GetString("ErrorContainingXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.gsmarena.com/acer-phones-59.php
        ///https://www.gsmarena.com/alcatel-phones-5.php
        ///https://www.gsmarena.com/allview-phones-88.php
        ///https://www.gsmarena.com/amazon-phones-76.php
        ///https://www.gsmarena.com/amoi-phones-28.php
        ///https://www.gsmarena.com/apple-phones-48.php
        ///https://www.gsmarena.com/archos-phones-90.php
        ///https://www.gsmarena.com/asus-phones-46.php
        ///https://www.gsmarena.com/at&amp;t-phones-57.php
        ///https://www.gsmarena.com/benefon-phones-15.php
        ///https://www.gsmarena.com/benq-phones-31.php
        ///https://www.gsm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GsmArenaLinks {
            get {
                return ResourceManager.GetString("GsmArenaLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return ExecuteToList&lt;{1}&gt;(&quot;{0}&quot;, container.ToList());.
        /// </summary>
        public static string NewPattern {
            get {
                return ResourceManager.GetString("NewPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable table = ExecuteToTable\(&quot;(?&lt;spname&gt;\w+)&quot;, container.ToList\(\)\);
        ///
        ///return MapAll&lt;(?&lt;classname&gt;\w+)&gt;\(table\);.
        /// </summary>
        public static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///[&quot;Kanji&quot;,&quot;Stroke&quot;,&quot;Radicals&quot;],
        ///[&quot;一&quot;,1,[1]],
        ///[&quot;丶&quot;,1,[3]],
        ///[&quot;丿&quot;,1,[4]],
        ///[&quot;乙&quot;,1,[5]],
        ///[&quot;亅&quot;,1,[6]],
        ///[&quot;丁&quot;,2,[1,6]],
        ///[&quot;七&quot;,2,[4,5,25]],
        ///[&quot;乂&quot;,2,[3,4]],
        ///[&quot;乃&quot;,2,[1,2,4,36]],
        ///[&quot;九&quot;,2,[34]],
        ///[&quot;了&quot;,2,[1,6]],
        ///[&quot;二&quot;,2,[7]],
        ///[&quot;亠&quot;,2,[8]],
        ///[&quot;人&quot;,2,[9]],
        ///[&quot;儿&quot;,2,[12]],
        ///[&quot;入&quot;,2,[13]],
        ///[&quot;八&quot;,2,[14]],
        ///[&quot;冂&quot;,2,[16]],
        ///[&quot;冖&quot;,2,[17]],
        ///[&quot;冫&quot;,2,[18]],
        ///[&quot;几&quot;,2,[19]],
        ///[&quot;凵&quot;,2,[20]],
        ///[&quot;刀&quot;,2,[21]],
        ///[&quot;力&quot;,2,[23]],
        ///[&quot;勹&quot;,2,[24]],
        ///[&quot;匕&quot;,2,[25]],
        ///[&quot;匚&quot;,2,[26]],
        ///[&quot;匸&quot;,2,[26]],
        ///[&quot;十&quot;,2,[27]],
        ///[&quot;卜&quot;,2,[28]],
        ///[&quot;卩&quot;,2,[29]],
        ///[&quot;厂&quot;,2,[30]],
        ///[&quot;厶&quot;,2,[31]],
        ///[&quot;又&quot;,2,[32]] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RadicalsKanji {
            get {
                return ResourceManager.GetString("RadicalsKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows -&quot;windows 10&quot; -server -xp.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Lorem Ipsum?
        ///
        ///Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&apos;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SomeBigText {
            get {
                return ResourceManager.GetString("SomeBigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;o&quot;: [
        ///		{ &quot;a&quot;: &quot;3&quot; },
        ///		{ &quot;a&quot;: 67 },
        ///		{ &quot;a&quot;: -98 }
        ///	]
        ///}.
        /// </summary>
        public static string SomeJson {
            get {
                return ResourceManager.GetString("SomeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 10 Pro v.1511 En-us x64 July2016 Pre-Activated-=TEAM OS=	2990	136
        ///Windows 7 SP1 Ultimate (64 Bit)	1649	99
        ///KMSpico 10.1.8 FINAL + Portable (Office and Windows 10 Activator	1275	36
        ///Windows Loader v2 2 2 by Daz	1068	2
        ///Microsoft Windows 10 Home and Pro x64 Clean ISO	991	60
        ///WINDOWS 8.1 PRO x64-ACTIVATED(EXCELLENT)	831	61
        ///World of Warcraft Client - Version 1.12.1 enUS - Windows	825	13
        ///Windows 7 SP1 Ultimate (32 Bit)	824	37
        ///Windows 7 Ultimate SP1 PT-BR x64 ISO	775	63
        ///Microsoft Toolkit 2.6.2 Final (Windows  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SomeTabbedText {
            get {
                return ResourceManager.GetString("SomeTabbedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // comment
        ///
        ///DataTable table = ExecuteToTable(&quot;Brand_Select&quot;, container.ToList());
        ///
        ///return MapAll&lt;Brand&gt;(table);
        ///
        ///// comment
        ///
        ///DataTable table = ExecuteToTable(&quot;Other_StoredProcedure&quot;, container.ToList());
        ///
        ///return MapAll&lt;OtherClass&gt;(table);.
        /// </summary>
        public static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
    }
}
